### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by romgrk-comparative** [igormironchik/args-parser#11]
Hi,

This args parser looks great, but would it be possible to document all the features more exhaustively?

Thanks.

**Comment by igormironchik** [comment]
Hi,

Could you point to concrete features that should to be more documented?

**Comment by romgrk-comparative** [comment]
How to print the help. I've switched to CLI11 meanwhile so I'm not using this anymore :|

**Comment by igormironchik** [comment]
Nothing simpler then print help in `args-parser`.

```cpp
CmdLine cmd( argc, argv );

cmd.addArgWithFlagAndName( 'b', "bool", false, false, "Boolean flag",
    "Boolean flag, used without value" )
  .addArgWithFlagAndName( 'v', "value", true, false, "With value",
    "Argument with value", "", "VAL" )
  .addHelp( true, argv[ 0 ], "CLI with boolean and value." );

cmd.parse();
```

Below line:

```cpp
.addHelp( true, argv[ 0 ], "CLI with boolean and value." );
```

just adds `-h, --help` argument that will print help.

And keep in mind that help in `args-parser` is aligned, you can write so much long description as you want and help will be pretty printed. I lost a lot of time on it. Help is one of the powerful sides of this library...

I don't see needs to write additional documentation on this question, as all is fine written.

>  * args-parser provides `Help` argument that provides help printing. `Help`
> uses `-h, --help` arguments. `Help` can receive value with name
> of argument or command to print help about. If `Help` receives the name
> of a command as the value, then the name of a subcommand or a child argument
> can also be provided as the next value, to get help about the subcommand/child argument.

**Comment by romgrk-comparative** [comment]
How to do it programatically, in case an exception is caught.

**Comment by igormironchik** [comment]
Well, it's rare use case, but it's doable.

You can use `HelpPrinter` class for this.

```cpp
using namespace Args;

HelpPrinter printer;
printer.setExecutable( "..." );
printer.setAppDescription( "..." );
printer.setLineLength( length );
printer.setCmdLine( cmd );

printer.print( outStream() );
```

**Comment by igormironchik** [comment]
Thank you for this point of view. Never thought that somebody will want to print help programmatically. Done in Q/A section.
