### ISSUE TITLE
Shadowed declaration

### ISSUE THREAD

**Issue by rbu9fe** [igormironchik/args-parser#14]
I'm playing around with the args-parser and our (quite restrictive) compiler settings generate a compilation error in help_printer.hpp at line 638:
`declaration of 'cmd' shadows a previous local [-Werror=shadow]`
Perhaps you should rename the lambda function's argument `cmd`.

**Comment by igormironchik** [comment]
I'm out of home till monday, can't have a look at the issue. Be patient, will do as soon as possible.

**Comment by igormironchik** [comment]
Fixed in commit 2e4d55d

I won't do any release for so small issue. Please checkout latest commit from repo.
