### ISSUE TITLE
Is the related to `qtargparser`?

### ISSUE THREAD

**Issue by barracuda156** [igormironchik/args-parser#15]
Is this the same with http://code.google.com/p/qtargparser or another one? Google Code redirected me here.

**Comment by igormironchik** [comment]
Hello, I forgot about `QtArg` almost. `QtArg` (`qtargparser`) is a father of this repository. `QtArg` was transformed to `Args` (`args-parser`). It can be used with Qt too. But this repository is very refactored. It even not `API` compatible. With Qt you can use built-in argument parser.

Why do you ask it?

**Comment by barracuda156** [comment]
@igormironchik I was looking for projects which implemented some functionality of Qt5 in a way it can be used in Qt4. (In order to make it easier to adapt code written for Qt5 for building with Qt4.)

**Comment by igormironchik** [comment]
Uh, not sure if `args-parser` can be built with Qt4. With Qt5 possibly, don't remember... Try it yourself, anyway you will need to rewrite arguments handling, `args-parser` is not `API` compatible with `QCommandOption`... But it's doable, if `args-parser` will be built with Qt4.

**Comment by barracuda156** [comment]
By the way, do you still have the old Qt4-compatible version of this somewhere (as a source code)?

**Comment by igormironchik** [comment]
No.

**Comment by igormironchik** [comment]
I guess you don't have more questions... Reopen if you do.

**Comment by barracuda156** [comment]
> I guess you don't have more questions... Reopen if you do.

Yeah, no more as of now. Thank you.
