### ISSUE TITLE
Name clashes if a class Command is declared in the global namespace

### ISSUE THREAD

**Issue by wegugin** [igormironchik/args-parser#16]
I've integrated the library v. 6.3.3 in a project, where one of the classes in the global namespace is named Command. This shouldn't be a problem, as the entire args-parser lirary is implemented in the namespace Args.
However, the class Args::ArgIface declares the class Commad to a friend:
```
class ArgIface {
	friend class CmdLine;
	friend class GroupIface;
	friend class Command; // this is meant to be Args::Command, not ::Command!
...
```
Because this is done before the class Args::Command declaration and after ::Command declaration, the compiler makes ::Command a friend instead of Args::Command. This leads to the protected member access compilation error.
The solution is to use a forward declaration of Command just before ArgIface declaration. Probably the same should be done to GroupIface (CmdLine is already forward-declared). Forward declaration makes the compiler aware of Args::Command class, and it is able to pick the correct one to make friend when declaring Args::ArgIface as expected.

**Comment by igormironchik** [comment]
Hello.

Could you provide minimal reproducible example (in one `main.cpp`)?

Thank you.

**Comment by wegugin** [comment]
Hi, sure, here it is:

```
#include <stdlib.h>

class Command
{
public:
    int GetSomething() const {return m_something;};

private:
    const int m_something = 5;
};

#include <all.hpp>

class CommandLine : public ::Command
{
public:
    void ProcessCl(int argc, char ** argv)
    {
        std::cout << "something is" << GetSomething() << std::endl;
        Args::CmdLine cmd(argc, argv);
        cmd
            .addCommand("command", Args::ValueOptions::NoValue, false, "just some command")
            .addArgWithFlagAndName('a', "arg", false, false, "optional argument")
            .end();
        cmd.parse();

        if(cmd.isDefined("command"))
        {
            std::cout << "found command" << std::endl;
        }
        if (cmd.isDefined("-a"))
        {
            std::cout << "found argument arg" << std::endl;
        }
    };
};

int main(int argc, char ** argv)
{
    CommandLine cl;
    cl.ProcessCl(argc, argv);

    return 0;
}
```
Note, I put `#include <all.hpp>` after the ::Command class declaration. Otherwise the compiler picks the correct class as a friend.
I'm using an MSVC compiler, but I think, the behavior would be the same with any compiler.

**Comment by igormironchik** [comment]
Agreed, with `MSVC` issue exists. With `GCC` everything is fine. Not sure who is right here. Anyway I fixed issue with `MSVC`. The commit is in repository.

**Comment by wegugin** [comment]
Thanks for fixing it! I guess, this is one of those things that are compiler implementation dependent.
And thank you a lot for maintaining the library, it's really handy in small projects.
