### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by zamazan4ik** [igormironchik/args-parser#2]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by igormironchik** [comment]
I don't see an urgent need for this. But I'll think.

**Comment by igormironchik** [comment]
https://bintray.com/igormironchik/public/Args%3Aigormironchik

**Comment by zamazan4ik** [comment]
@igormironchik Thank you a lot! Do you want to push it into bincrafters repo?

**Comment by igormironchik** [comment]
Well, why not? I'm absolutely new to Conan, so what does bincrafters repo give? What benefits? I published Args in my own repo and asked to add Args to Conan Center...

**Comment by zamazan4ik** [comment]
Ahh, you already asked about adding Args recipe to Conan center - great! In this case there is no any reason in bincrafters repo. I hope your library will be added to conan-center ASAP.

**Comment by igormironchik** [comment]
Hello,

Args already in the Conan Center.

https://bintray.com/conan/conan-center?filterByPkgName=Args%3Aigormironchik

**Comment by zamazan4ik** [comment]
@igormironchik Thank you a lot :-)
