### ISSUE TITLE
Missing explanation regarding difference from other libraries

### ISSUE THREAD

**Issue by eyalroz** [igormironchik/args-parser#3]
There exist several and apparent;y more popular libraries for parsing command-line arguments e.g.:

* [`boost::program_options`](https://github.com/boostorg/program_options)
* [`CLI11`](https://github.com/CLIUtils/CLI11)
* [`Poco Application`](https://github.com/pocoproject/poco/blob/master/Util/include/Poco/Util/Application.h) (yuck)

and probably others. Your `README.md` should explain you your conception of command-like argument parsing is different than theirs.

**Comment by igormironchik** [comment]
Parsing of command line arguments is simple task on one sight, but from another hand it's more complicated than you can imagine. Try to architect such library that will fit any possible use case, and don't forget about printing of help message. Interesting, isn't it? But it's impossible.

Any such library has strong and weak sides. But in most cases developers need simple list of arguments, and here absolutely any library for parsing command line arguments can help him. Do you use Boost in your project? Use boos::program_options. Do you use Poco? Use it.

In my library I tried to implement most usable command line features with the rest of printing good and readable help message. In my opinion help message is the main in command line parsing libraries. I tried to be very user friendly in this question.

What about comparing with another libraries?! This is like how much sugar to put into tea. Let it be so like now. Anyone who stumbles on something and finds my library better is welcome.

**Comment by eyalroz** [comment]
I realize command-line argument parsing is far from trivial, and there are different possible design choices to make. But - there needs to be some motivation for trying an alternative. It's not like "more sugar" or "less sugar". Suppose someone showed you two boxes of tea - with no graphic or explanatory text on cover. It's just "Mironchik Tea" vs "Boost PO Tea"... you should really write something on the box.

**Comment by igormironchik** [comment]
Are you happy with "Boost PO Tea"? Let it be so. I believe that described very well Args in README and documentation. I won't compare with other libraries. You will never know what tea do you prefer more until you try all, and don't believe what's written on the box...

**Comment by igormironchik** [comment]
Hello. I think again about your words. Probably you are right... I need to add some words with comparing with another libraries.

I have a question to you. I looked at boost::po and can't find a possibility to add commands in cli.

For example, implement cli like in `git`

```
git add -A
git commit
...
```

In my parser I have such possibility. I have `Command` and `ArgAsCommand` classes...

And I format help output automatically. It looks nice, it's aligned. Developer should only set the line length (by default 80 characters)...

I don't want to look closer at boost::po. If you are experienced with it. Could you comment?

**Comment by igormironchik** [comment]
Hello.

I added this paragraph to README...

Why should I use this library?

 * There are tons of libraries for parsing command line arguments in the
Internet. But Args provides possibility to define commands, for example

    ```
    git add -A
    git commit
    git push
    ```

    Help output is very user-friendly. I tried to do help very useful for user.

    If you need only simple arguments in style `--do-it <value>` then possibly
    you will find another library more useful for you, but who knows...

**Comment by igormironchik** [comment]
Could you point me to library that provides ability to define commands and sub-commands? Do that libraries print user-friendly help?

But I agree with you. `ArgAsCommand` is not fully featured sub-command, as it can't have children... I should review the library for this case.

**Comment by eyalroz** [comment]
That's just a comparison of a single feature to a single library. That's really not sufficient - not to mention the fact that other argument parsing libraries do offer a "subcommands" feature.

**Comment by eyalroz** [comment]
I think [Lyra](https://github.com/bfgroup/Lyra) supports them.

**Comment by igormironchik** [comment]
> I think [Lyra](https://github.com/bfgroup/Lyra) supports them.

I don't think so... There is no even commands, there is only `arg`, what I can't name command...

**Comment by igormironchik** [comment]
If you are interested, I did fully featured sub-commands in the dev branch. Not fully tested yet, but as preview... I fully refused from `ArgAsCommand`. Now `Command` can be nested so much as you need.

```cpp
CmdLine cmd( argc, argv, CmdLine::CommandIsRequired );

Command add( SL( "add" ), ValueOptions::NoValue, true );
add.setDescription( SL( "Add item." ) );
add.setLongDescription( SL( "Add item for monitoring. The type "
	"of item is defined by subcommand." ) );

Command del( SL( "del" ), ValueOptions::NoValue, true );
del.setDescription( SL( "Delete item." ) );
del.setLongDescription( SL( "Delete item from monitoring. The type "
	"of item is defined by subcommand." ) );

Command file( SL( "file" ), ValueOptions::ManyValues );
file.setDescription( SL( "File item." ) );
file.setLongDescription( SL( "File item to work with." ) );
file.setValueSpecifier( SL( "fn" ) );

add.addCommand( file );
del.addCommand( file );

Help help;
help.setAppDescription(
	SL( "This application just show power of the Args help." ) );
help.setExecutable( argv[0] );

cmd.addArg( add );
cmd.addArg( del );
cmd.addArg( help );

cmd.parse();
```

And the help looks like:

```
./example.with_commands -h
This application just show power of the Args help. 

USAGE: ./example.with_commands <command> <options>

  add Add item. 
  del Delete item. 

OPTIONAL:
 -h, --help <arg> Print this help. 
```

and

```
./example.with_commands -h add
Add item for monitoring. The type of item is defined by subcommand. 

USAGE: add <command>

  file <fn> File item. 

GLOBAL OPTIONAL:
 -h, --help <arg> Print this help.
```

```
./example.with_commands -h add file
File item to work with. 

USAGE: file <fn> <options>

GLOBAL OPTIONAL:
 -h, --help <arg> Print this help.
```

Not bad, do you agree?
