### ISSUE TITLE
connecting args and commands to functions

### ISSUE THREAD

**Issue by ThePreviousOne** [igormironchik/args-parser#5]
I am fully aware that this is a stupid question (but I also know I won't figure it out on my own)

I can't figure out how to connect and of my defined argument to actual functions to do anything useful
ie. `unzip extract some-file` or `unzip -c directory` would extract and compress things respectively
or even to set a value like in the help example `example.help --host localhost --port 44` could set `int port = 44`

This looks like a cool library, and I plan to use it in a lot of current and past projects once I know how.

**Comment by igormironchik** [comment]
Hello. You are welcome.

It's better to see the code once, look...

```cpp
#include <args-parser/all.hpp>

using namespace Args;

int main( int argc, char ** argv )
{
	try {
		CmdLine cmd( argc, argv ); // Note: we don't set that command is required.

		cmd.addCommand( "extract", ValueOptions::OneValue,
				false, "Extract file", "", "", "fn" )
			.end()
			.addCommand( "compress", ValueOptions::OneValue,
				false, "Compress file", "", "", "fn" )
			.end()
			.addArgWithFlagOnly( 'c', true, false, "Compress file",
				"Compress file or folder", "", "fn" )
			.addHelp( true, argv[ 0 ], "unzip application" );

		cmd.parse();

		if( cmd.isDefined( "extract" ) )
		{
			const auto fn = cmd.value( "extract" );

			outStream() << "Extracting file \"" << fn << "\"\n";

			return 0;
		}
		else if( cmd.isDefined( "-c" ) || cmd.isDefined( "compress" ) )
		{
			// As we have the same action with command and option
			// we can do here with different approaches.
			// For example I implemented it so that compression will be
			// in action for both if they defined.
			if( cmd.isDefined( "-c" ) )
			{
				const auto fn = cmd.value( "-c" );

				outStream() << "Compressing file \"" << fn << "\"\n";
			}

			if( cmd.isDefined( "compress" ) )
			{
				const auto fn = cmd.value( "compress" );

				outStream() << "Compressing file \"" << fn << "\"\n";
			}

			return 0;
		}
		else {
			outStream() << "Please specify command or option\n";

			return 1;
		}
	}
	catch( const HelpHasBeenPrintedException & )
	{
		return 0;
	}
	catch( const BaseException & x )
	{
		outStream() << x.desc() << std::endl;

		return 1;
	}
}
```

**Comment by igormironchik** [comment]
I realized that groups in `args-parser` don't support commands in them. I need to think on it. This is not a bug, library is in OK state, but it would be better if we can define `OnlyOneGroup` with command and option, in our example these are `compress` and `-c`. I will think on this feature...

**Comment by igormironchik** [comment]
I will release new version soon, where will be possible to do so:

```cpp
CmdLine cmd( argc, argv );

cmd.addCommand( "extract", ValueOptions::OneValue,
		false, "Extract file", "", "", "fn" )
	.end()
	.addOnlyOneGroup( "use command or option, not both" )
		.addCommand( "compress", ValueOptions::OneValue,
			false, "Compress file", "", "", "fn" )
		.end()
		.addArgWithFlagOnly( 'c', true, false, "Compress file",
			"Compress file or folder", "", "fn" )
	.end()
	.addHelp( true, argv[ 0 ], "unzip application" );
```

And then:

```cpp
if( cmd.isDefined( "extract" ) )
{
	const auto fn = cmd.value( "extract" );

	outStream() << "Extracting file \"" << fn << "\"\n";

	return 0;
}
else if( cmd.isDefined( "-c" ) )
{
	const auto fn = cmd.value( "-c" );

	outStream() << "Compressing file \"" << fn << "\"\n";

	retrun 0;
}
else if( cmd.isDefined( "compress" ) )
{
	const auto fn = cmd.value( "compress" );

	outStream() << "Compressing file \"" << fn << "\"\n";

	return 0;
}
else {
	outStream() << "Please specify command or option\n";

	return 1;
}
```

**Comment by igormironchik** [comment]
Commit with this nice feature is in master. I need to test a little more before release...

Do you have any more questions? Feel free to ask, will be very glad to answer.

**Comment by ThePreviousOne** [comment]
Thank you, for your help, and for answering so quickly.
I was just missing `isDefined()`
~I don't really get what a Group is? Sorry I'm still a beginner.~

Also your formatting make `compress` look like a sub-command of `extract`, I know it's not but at first glance it appears that way.

**Comment by ThePreviousOne** [comment]
~I'd be happy to help with testing if you like, all of my programs are currently for personal use as well as in constant development. Also I use them on a daily basis so I don't have to worry about other users encountering bugs.~

I'm using the master branch so I'm already doing that

**Comment by igormironchik** [comment]
Great, you are welcome, feel free to post issues.
