### ISSUE TITLE
Use Case for redefining arguments

### ISSUE THREAD

**Issue by ThePreviousOne** [igormironchik/args-parser#8]
I have in my program 2 arguments that should Ideally work with a command to achieve different behavior than if used alone.
the idea is that if used alone the load specific files but if used as arguments of the `init` command would set the location of those files.
I don't know if this would be a common use case, but I thought it might be worth mentioning.

**Comment by ThePreviousOne** [comment]
I thought about (havent looked to see if its possible or tried it yet) initalizing the `Arg`s using the old api and adding them with everything else VIA the new API

My thinking was that, that way they wouldn't be redefined and I could still use the new API which looks cleaner and I'm already using.

**Comment by ThePreviousOne** [comment]
Could this work without redefing the args?

**Comment by igormironchik** [comment]
I see, you want to have something similar to:

```
program.exe --file my_file.txt
```

and

```
program.exe init --file my_file.txt
```

Such redefinition is blocked by me because `--file` under `init` command conflicts with global argument `--file`. You won't be able to do so neither with old syntax nor with new one.

Ok, I see. And now I think that it can be useful. Will think on it tomorrow. Today is Sunday - Holy Day. Have a good weekend!

**Comment by igormironchik** [comment]
But `--file` can be redefined under different command...

```
program.exe init --file my_file.txt
```

and

```
program.exe dowork --file my_file.txt
```

is allowed now.

**Comment by ThePreviousOne** [comment]
that could work it would avoid the need to redefine the argument as you could just use a broader description from the start

**Comment by igormironchik** [comment]
> Could this work without redefing the args?

No. The redefinition should be, but it's disallowed.

But you can use the same argument under different commands, but in this case help messages will be the same. The redefinition is better...

**Comment by igormironchik** [comment]
Parser does not allow to use argument with the same name in global space and under command. But I guess, that this is a mistake, Why not? `--file` under command - is one thing and `--file` in global space is another one... Thank you that pointed me to it.

**Comment by igormironchik** [comment]
My idea was that under command user can use global arguments. And here a collision occurs.

**Comment by igormironchik** [comment]
I'm at a loss what would be better...

**Comment by igormironchik** [comment]
Stop! What is stopping to do so?

```cpp
cmd.addArgWithFlagAndName( 'f', "file", ....)
    .addCommand( "init", ... )
```

Here you will be able to use `--file` under command and in global space.

But do so:

```cpp
if( cmd.isDefined( "init" ) )
{
    if( cmd.isDefined( "--file" ) )
    {
    }
}
else if( cmd.isDefined( "--file" ) )
{
}
```

In such case

```
program.exe --file my_file.txt
program.exe init --file my_file.txt
```

are legal both.

**Comment by igormironchik** [comment]
I wrote that

```cpp
cmd.addArgWithFlagOnly( 'f', ... )
    .addCommand( "init" )
        .addArgWithFlagOnly( 'f', ... )
    .end();
```

Will lead to exception that argument `-f` is redefined. But have a look at my previous comment...

And I'm thinking now what would be better: leave as is or allow such redefinition.

What do you think?

**Comment by ThePreviousOne** [comment]
what if args and commands were organized into subsets of groups and `checkCorrectnessBeforeParsing` ran and stored separately for each? Correct me if i'm wrong but it kind looks like they are all done in one big blob at the same time
then the same could be done for commands and args that were subsets of other commands.

What to do depends on how much work it is I guess.

**Comment by igormironchik** [comment]
> what if args and commands were organized into subsets of groups and `checkCorrectnessBeforeParsing` ran and stored separately for each? Correct me if i'm wrong but it kind looks like they are all done in one big blob at the same time then the same could be done for commands and args that were subsets of other commands.

You are right, check before parsing is done in one big blob. I can't catch your mind. What will give us if we will separate this process? Why do we need it?

Explain, please, what do you want to get in command line? Show examples.

> What to do depends on how much work it is I guess.

Don't agree, this change is about a few hours. But I'm not sure needed it or no...

**Comment by ThePreviousOne** [comment]
```
                .addOnlyOneGroup(groupDesc)
                    .addArgWithFlagAndName('d', "password", true, false,
                            "Search Password file", "Contains Site Passwords", "", "VALUE")
                    .end()
                    .addArgWithFlagAndName('s', "ssh", true, false,
                            "Search SSH Keys file", "", "", "VALUE")
                    .end()
                    .addArgWithFlagAndName('l', "local", false, false,
                            "Print out Local Password file", "Contains User Passwords", "", "")
                    .end()
                .end()
                .addCommand("init", Args::ValueOptions::NoValue, false,
                        "Setup Configuration", "", "", "ARG")
                    .addCommand("d", Args::ValueOptions::OneValue, false,
                            "Configure Password file Location", "", "", "VALUE")
                    .end()
                    .addCommand("s", Args::ValueOptions::OneValue, false,
                            "Configure SSH key file Location", "", "", "VALUE")
                    .end()
```
would allow me to run `program init -s somefile` to set the location of the file and `program -s somekey` to read that key from the file.
Im currently using  `program init s somefile` which works obviously but its only a work around.

I cant think of a specific use case for my proposed solution but it would allow `program command --arg` as well as `program cmd --arg` and `program --arg` where arg operated slightly differently for each.

as to what I meant I was thinking of storing a map of vector<ArgIface> 's for each group. Thus separating all the args and command based on group so the would actually be unique and not redefinition

**Comment by igormironchik** [comment]
Will be step by step.

```cpp
.addOnlyOneGroup(groupDesc)
    .addArgWithFlagAndName('d', "password", true, false,
        "Search Password file", "Contains Site Passwords", "", "VALUE")
    .end()
    .addArgWithFlagAndName('s', "ssh", true, false,
        "Search SSH Keys file", "", "", "VALUE")
    .end()
    .addArgWithFlagAndName('l', "local", false, false,
        "Print out Local Password file", "Contains User Passwords", "", "")
    .end()
.end()
```

you have a mistake here: `end()` needed only for groups and commands (that are groups too). So to work `OnlyOneGroup` properly you should do so:

```cpp
.addOnlyOneGroup(groupDesc)
    .addArgWithFlagAndName('d', "password", true, false,
        "Search Password file", "Contains Site Passwords", "", "VALUE")
    .addArgWithFlagAndName('s', "ssh", true, false,
        "Search SSH Keys file", "", "", "VALUE")
    .addArgWithFlagAndName('l', "local", false, false,
        "Print out Local Password file", "Contains User Passwords", "", "")
.end()
```
... but this is my omission in the documentation ...

Why you don't want to do so:

```cpp
                .addOnlyOneGroup(groupDesc)
                    .addArgWithFlagAndName('d', "password", true, false,
                            "Search Password file", "Contains Site Passwords", "", "VALUE")
                    .addArgWithFlagAndName('s', "ssh", true, false,
                            "Search or configure SSH Keys file", "Use with command \"init\" to configure "
                            "location of the key file and standalone to search the key.", "", "VALUE")
                    .addArgWithFlagAndName('l', "local", false, false,
                            "Print out Local Password file", "Contains User Passwords", "", "")
                .end()
                .addCommand("init", Args::ValueOptions::NoValue, false,
                        "Setup Configuration", "", "", "ARG")
```

```cpp
if( cmd.isDefined( "init" ) )
{
    if( cmd.isDefined( "-s" ) )
    {
        configureSSHKeyFile( cmd.value( "-s" ) );
    }
}
else if( cmd.isDefined( "-s" ) )
{
    readSSHKeyFile( cmd.value( "-s" ) );
}
```

**Comment by ThePreviousOne** [comment]
I tried that but it didn't recognize the flag, I forget what happened, I'll fix the `end()` thing and try it again

**Comment by igormironchik** [comment]
Will check your example...

**Comment by igormironchik** [comment]
```cpp
try {
		CmdLine cmd( argc, argv );

		cmd.addOnlyOneGroup("")
				.addArgWithFlagAndName('d', "password", true, false,
						"Search Password file", "Contains Site Passwords", "", "VALUE")
				.addArgWithFlagAndName('s', "ssh", true, false,
						"Search or configure SSH Keys file", "Use with command \"init\" to configure "
						"location of the key file and standalone to search the key.", "", "VALUE")
				.addArgWithFlagAndName('l', "local", false, false,
						"Print out Local Password file", "Contains User Passwords", "", "")
			.end()
			.addCommand("init", Args::ValueOptions::NoValue, false,
					"Setup Configuration", "", "", "ARG")
			.end()
			.addHelp( true, argv[ 0 ], "Application to work with SSH keys" );

		cmd.parse();

		if( cmd.isDefined( "init" ) )
		{
			if( cmd.isDefined( "-s" ) )
			{
				outStream() << "configure " << cmd.value( "-s" ) << "\n";
			}
		}
		else if( cmd.isDefined( "-s" ) )
		{
			outStream() << "read " << cmd.value( "-s" ) << "\n";
		}
	}
	catch( const HelpHasBeenPrintedException & )
	{
	}
	catch( const BaseException & x )
	{
		outStream() << x.desc() << SL( "\n" );
	}
```

It works, but I caught a bug with help... Give me an hour.

**Comment by igormironchik** [comment]
I did a commit 65b47130b1399f33c65bbee3a2fb7a84b4cce83d

There fixed help printing for case with global argument under command. And now it's impossible to mess with `end()` methods, if you will do mistake you won't compile...

**Comment by igormironchik** [comment]
I'm very glad to receive a real feedback from you. I'm not very good tester, and your real experience caught a bug in help printing and I did two improvements. Thanks. :)

**Comment by ThePreviousOne** [comment]
No problem, Happy to help

**Comment by ThePreviousOne** [comment]
Oh I found a possible use case for redefining args. I have a flag `-i` (and a command `insert` but thats not my point) for inserting new values into the password file. Now though with the addition of `-s` it would be cool to do `-is` to insert into the SSH key file and `-ip` to insert to the password file

**Comment by igormironchik** [comment]
Where is redefinition necessary? Is `-i` a global flag? You can do like this:

```cpp
cmd.addArgWithFlagOnly( 'i' )
    .addArgWithFlagOnly( 's' );

cmd.parse();

if( cmd.isDefined( "-i" ) )
{
    if( cmd.isDefined( "-s" ) )
    {
        insertIntoSSHkey( cmd.value( "-s" ) );
    }
}
else if( cmd.isDefined( "-s" ) )
{
    readSSHKeyFile( ... );
}
```

**Comment by ThePreviousOne** [comment]
ya I realized after I posted that

**Comment by igormironchik** [comment]
Ok. I go into bed. Good night.
